service: namewhisk-pubsub

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

custom:
  stage: dev
  debug: "*"
  deploymentBucket: 'global-deployment-bucket'
  dotenv:
    path: ./.env
    include:
      - AWS_IOT_HOST
      - REDIS_URL
  namewhisk:
    functions:
      - run

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-east-1
  profile: default
  deploymentBucket:
    name: ${self:custom.deploymentBucket}
  environment:
    DEBUG: ${self:custom.debug}
  apiKeys:
    - ${self:custom.stage}-namewhisk-session-key
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    - Effect: "Allow"
      Action:
        - "iot:Connect"
        - "iot:Publish"
        - "iot:Subscribe"
        - "iot:Receive"
        - "iot:GetThingShadow"
        - "iot:UpdateThingShadow"
      Resource: "*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "route53domains:*"

functions:
  run:
    memorySize: 1536
    timeout: 300
    handler: src/run.handler
    events:
      - iot:
          sql: "SELECT * FROM 'namewhisk/new-session'"
  session:
    memorySize: 128
    timeout: 10
    handler: src/session.handler
    events:
      - http:
          method: OPTIONS
          path: /
          cors: true
      - http:
          method: GET
          path: /
          cors: true
  disconnect:
    memorySize: 256
    handler: src/disconnect.handler
    timeout: 10
    events:
      - iot:
          sql: "SELECT * FROM 'namewhisk/last-will'"

resources:
  Resources:
    RunLogGroup:
      Properties:
        RetentionInDays: 7
    SessionLogGroup:
      Properties:
        RetentionInDays: 7
    DisconnectLogGroup:
      Properties:
        RetentionInDays: 7