service: domain-redis-cache

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: 'us-east-1'
  memorySize: 512
  timeout: 30
  environment:
    cacheUrl: ${cf:domain-redis-cache-dev.cacheUrl}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "logs:*"
        - "ec2:*"
      Resource: '*'
  vpc:
    securityGroupIds:
      - ${cf:domain-redis-cache-dev.VPCSecurityGroup}
      - ${cf:domain-redis-cache-dev.RedisSecurityGroup}
    subnetIds:
      - ${cf:domain-redis-cache-dev.PrivateSubnetA}
      - ${cf:domain-redis-cache-dev.PrivateSubnetB}

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: get/{id}
          method: GET
          cors: true
  post:
    handler: handler.post
    events:
      - http:
          path: post/{id}
          method: POST
          cors: true

resources: ${file(./resource.json)}
