service: namewhisk-graphql-api

plugins:
  - serverless-plugin-typescript

custom:
  stage: prod
  debug: "*"
  deploymentBucket: 'global-deployment-bucket'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-east-1
  disableLogs: false
  logRetentionInDays: 7
  deploymentBucket:
    name: ${self:custom.deploymentBucket}

functions:
  handler:
    handler: src/handler.handler
    events:
      - http:
          path: graphql
          method: any
          integration: lambda-proxy
          cors: true

resources:
  Resources:
    HandlerLogGroup:
      Properties:
        RetentionInDays: 7